# Generated by Django 3.2.7 on 2021-09-10 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='produtos')),
                ('preco_mercado', models.PositiveIntegerField()),
                ('venda', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('garantia', models.CharField(blank=True, max_length=300, null=True)),
                ('devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('visualização', models.PositiveIntegerField(default=0)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ordem_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenado', models.CharField(max_length=10)),
                ('endereço_envio', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereço_saida', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido caminho', 'Pedido caminho'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50)),
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereço', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='carrinhoproduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.produto')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carrinho')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojaapp.clientes'),
        ),
    ]
