# Generated by Django 3.2.7 on 2021-09-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
