# Generated by Django 3.2.7 on 2021-09-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0004_rename_carrinhoproduto_carroproduto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Carrinho',
        ),
    ]
