# Generated by Django 3.2.7 on 2021-09-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0005_rename_carro_carrinho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrinho',
            new_name='Carro',
        ),
    ]
