# Generated by Django 3.2.7 on 2021-09-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0006_rename_carrinho_carro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='carrinho',
        ),
    ]
