# Generated by Django 3.2.7 on 2021-09-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0007_rename_carro_carrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojaapp.clientes')),
            ],
        ),
        migrations.AlterField(
            model_name='carroproduto',
            name='carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro'),
        ),
        migrations.AlterField(
            model_name='ordem_pedido',
            name='carro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro'),
        ),
        migrations.DeleteModel(
            name='carrinho',
        ),
    ]
