# Generated by Django 3.2.7 on 2021-09-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0008_auto_20210918_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Carro1',
        ),
    ]
