# Generated by Django 3.2.7 on 2021-09-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0009_rename_carro_carro1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro1',
            new_name='carrinho',
        ),
    ]
